### PR TITLE
Supporting using git ssh url for bitbucket git checkouts

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by peter-edge** [comment]
Does it not need the `ssh://` for some reason? What about for mercurial (the function below)?

**Comment by bfosberry** [comment]
Yeah, bitbucket supports the git protocol with ssh keys, unsure about mercurial

**Comment by bfosberry** [comment]
More specifically, with ssh access the git protocol is required

**Comment by bfosberry** [comment]
Thanks!

**Pull request merged**
